# Generated by Django 4.1.13 on 2024-05-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image_url',
            new_name='imagename',
        ),
        migrations.RemoveField(
            model_name='book',
            name='follow_author',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
